spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/speednews
    username: speednews
    password: sbtm99!

  mail:
    host: smtp.gmail.com
    port: 587
    username: emptyspacefor91@gmail.com
    password: tylmkwpgtkifkzct
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:dev-secret-change-me}  # ← 환경변수 없으면 기본값 사용
    issuer: speednews
    accessTtlMinutes: 15
    refreshTtlDays: 14


logging:
  level:
    org.springframework.web: debug
    org.springframework.web.server.ResponseStatusException: debug
    org.springframework.security: debug
    doHoaSen.SpeedNews.auth: debug
    org.hibernate.SQL: debug    # SQL 로그 (개발 편의)
    org.hibernate.type.descriptor.sql: trace  # 바인딩 값까지 보고 싶으면 trace, 필요 없으면 제거
